### ISSUE TITLE
node 4.2.3

### ISSUE THREAD

**Issue by CitySim** [Nachbarshund/node-mssql-connector#10]
are there known issues with node version 4.2.3 (LTS)? 

i get errors when using node 4.2.3, i tried these versions:
* node-mssql-connector@0.2.0
* node-mssql-connector@0.3.0
* node-mssql-connector@0.4.0

```
/usr/build/node_modules/node-mssql-connector/lib/mssqlconnector.js:116
          connection.release();
                    ^

TypeError: Cannot read property 'release' of undefined
    at Object.callback (/usr/build/node_modules/node-mssql-connector/lib/mssqlconnector.js:116:21)
    at null._onTimeout (/usr/build/node_modules/node-mssql-connector/node_modules/tedious-connection-pool/lib/connection-pool.js:193:32)
    at Timer.listOnTimeout (timers.js:92:15)
```

```
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at ConnectionPool.addListener (events.js:239:17)
    at MSSQLRequestBase.exec (/usr/build/node_modules/node-mssql-connector/lib/mssqlconnector.js:101:27)
    at MSSQLRequestBase.exec (/usr/build/node_modules/node-mssql-connector/lib/mssqlconnector.js:3:61)
    at Schema.Entity._query (/usr/build/dynasiteNG/server/js/lib/entity.js:72:13)
    at Schema._query (/usr/build/dynasiteNG/server/js/lib/entity.js:3:59)
    at Schema.Entity._queryGet (/usr/build/dynasiteNG/server/js/lib/entity.js:374:12)
    at Schema._queryGet (/usr/build/dynasiteNG/server/js/lib/entity.js:3:59)
    at Schema.Materials.get (/usr/build/stylebase/server/js/modules/styles/materials/model.js:514:12)
    at Schema.get (/usr/build/stylebase/server/js/modules/styles/materials/model.js:3:59)
    at Array.async.auto._accessories (/usr/build/stylebase/server/js/modules/styles/model.js:1087:34)
    at listener (/usr/build/node_modules/async/lib/async.js:600:42)
    at /usr/build/node_modules/async/lib/async.js:542:17
    at _arrayEach (/usr/build/node_modules/async/lib/async.js:85:13)
    at Immediate.taskComplete (/usr/build/node_modules/async/lib/async.js:541:13)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by CitySim** [comment]
i tried again with node-mssql-connector@0.2.7, that version is working with node 4.2.3
